/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplicity;

import simplicity.Manager.Manager;
import simplicity.Save.*;
import simplicity.Sim.Sim;

public class App {
    public static long timeNow = 0; // time is in second

    public static void runTheTime() {
        Thread temp = new Thread() {
            public void run() {
                while (true) {
                    if (Manager.isThereAnyWorkingSim()) {
                        timeNow++;
                        Manager.clearScreen();
                        System.out.print(
                                Manager.getCurrentSim().getName() + " is " + Manager.getCurrentSim().getStatus());
                        long i = timeNow % 3;
                        if (i == 0) {
                            System.out.println(".");
                        } else if (i == 1) {
                            System.out.println("..");
                        } else {
                            System.out.println("...");
                        }
                        System.out.println("Time : " + timeNow);
                    }
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        temp.start();
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String args[]) {
        runTheTime();
        while (Manager.getGameStarted() == false) {
            Manager.gameMenu();
        }
        // generate the first sim. Otherwise, the game won't start
        if (Manager.getGameLoaded() == false) {
            Manager.generateSim();
        }
        // world will automatically generated in the manager
        while (Manager.canGameContinue()) {

            if(Manager.getCurrentSim().stillAlive()){
            if (Manager.isCurrentSimWorking()) {
                // can't do anything since the sim is still working
            } else {
                Manager.listCanDo();
                Manager.doQuery();
            }
            }else{
                // change the sim.
                Manager.changeSim();

            }
        }

        System.out.println("All of your sim is dead.");
        Manager.exitTheGame();
        // Manager.generateSim();
        // Save.save();
        // Sim sim = Load.load("data.json");
        // System.out.println(sim.getName());
    }
}
